### ISSUE TITLE
About voxel lighting

### ISSUE THREAD

**Issue by me66ccff** [AlexSTV/Voxelmetric#61]
Hello, I am 66ccff, I am making a game, I found your project, but I found the cave or the light is not correct, so I would like to ask you the progress, thank you

**Comment by me66ccff** [comment]
@AlexSTV Looking forward to your reply

**Comment by AlexSTV** [comment]
I disabled voxel lighting a while back because I didn't manage to resolve the performance issues of calculating lighting and decided to leave it on ice until more important parts are completed. The contents ofthe file are commented out at: https://github.com/AlexSTV/Voxelmetric/blob/alpha_2/Assets/Voxelmetric/Code/Utilities/BlockLight.cs but it hasn't been updated in a long time.

**Comment by me66ccff** [comment]
@AlexSTV  thank you ~~~
